import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Clock3, CreditCard, Globe2, Mail, MessageSquareText, UserRound, Users } from "lucide-react";
import { requireMembership } from "../../../../lib/auth";
import { createSupabaseServerClient } from "../../../../lib/supabase-server";
import { formatWhen } from "../../../../lib/dashboard-data";
import { getClientAppDetail } from "../../../../lib/client-data";
import { getActiveClientPlaybooks } from "../../../../lib/client-playbook-data";
import { ClientContactForm, ClientSlackAssignment, ClientSlackConnectLink, ClientStripeLink } from "../../../components/client-forms";
import { ClientPlaybookRunner } from "../../../components/client-playbook-controls";

export const dynamic = "force-dynamic";
export const maxDuration = 60;
export const metadata: Metadata = { title: "Client workspace" };

function money(amount: number | null, currency: string | null) {
  if (amount === null || !currency) return null;
  try { return new Intl.NumberFormat("en", { style: "currency", currency: currency.toUpperCase() }).format(amount / 100); }
  catch { return `${amount / 100} ${currency.toUpperCase()}`; }
}

export default async function ClientAppPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { membership } = await requireMembership();
  if (!membership) return null;
  const supabase = await createSupabaseServerClient();
  const [data, playbookData] = supabase ? await Promise.all([getClientAppDetail(supabase, membership.organization.id, id), getActiveClientPlaybooks(supabase, membership.organization.id)]) : [{ ready: false, app: null, messages: [], stripe: null }, { ready: false, playbooks: [] }];
  if (data.ready && !data.app) notFound();
  if (!data.app) return <main className="dashboard-main" id="main-content"><section className="panel setup-panel"><Users size={20} aria-hidden="true" /><div><strong>Client data is unavailable</strong><p>Apply migration 025, then refresh this page.</p></div></section></main>;
  const app = data.app; const contactsById = new Map(app.contacts.map(contact => [contact.id, contact]));
  const threadMap = new Map<string, typeof data.messages>();
  for (const message of data.messages) threadMap.set(message.threadKey, [...(threadMap.get(message.threadKey) || []), message]);
  const threads = [...threadMap.entries()].map(([key, messages]) => ({ key, messages, latest: messages[0] }));
  return <main className="dashboard-main" id="main-content">
    <Link className="back-row" href="/dashboard/clients"><ArrowLeft size={15} aria-hidden="true" />All clients</Link>
    <header className="client-detail-header"><span className="client-detail-icon"><Globe2 size={24} aria-hidden="true" /></span><div><p className="eyebrow">Existing client</p><h1>{app.name}</h1><a href={app.websiteUrl} target="_blank" rel="noreferrer">{app.websiteUrl}<ArrowUpRight size={14} aria-hidden="true" /></a></div><span className="status-badge status-active">{app.status}</span></header>
    <div className="client-detail-layout">
      <section className="client-main-column" aria-labelledby="correspondence-heading"><div className="section-heading"><div><p className="eyebrow">Yandex IMAP</p><h2 id="correspondence-heading">Email correspondence</h2></div><span className="count-badge">{threads.length} thread{threads.length === 1 ? "" : "s"}</span></div>
        {threads.length ? <div className="client-thread-list">{threads.map((thread, index) => { const participants = [...new Set(thread.messages.map(message => contactsById.get(message.clientContactId)?.name).filter(Boolean))]; const title = (thread.latest.subject || "No subject").replace(/^(\s*(?:re|fw|fwd)(?:\[[0-9]+\])?:\s*)+/i, "") || "No subject"; return <details className="client-thread" key={thread.key} open={index === 0}><summary className="client-thread-summary"><span className="client-thread-icon"><MessageSquareText size={17} aria-hidden="true" /></span><span className="client-thread-heading"><strong>{title}</strong><small>{participants.join(", ") || "Client"} · {thread.messages.length} message{thread.messages.length === 1 ? "" : "s"}</small></span><time dateTime={thread.latest.occurredAt}>{formatWhen(thread.latest.occurredAt)}</time></summary><ol className="client-message-list">{[...thread.messages].reverse().map(message => { const contact = contactsById.get(message.clientContactId); return <li key={message.id}><span className={`client-message-icon ${message.direction}`}><Mail size={15} aria-hidden="true" /></span><article><header><div><strong>{message.direction === "inbound" ? contact?.name || "Client" : "EpsiFlow"}</strong><span className={`status-badge status-${message.direction === "inbound" ? "replied" : "sent"}`}>{message.direction}</span></div><time dateTime={message.occurredAt}>{formatWhen(message.occurredAt)}</time></header><h3>{message.subject || "No subject"}</h3>{message.body ? <details><summary>Read message</summary><p>{message.body}</p></details> : <p className="muted">No plain-text body was available.</p>}</article></li>; })}</ol></details>; })}</div> : <div className="empty-state client-correspondence-empty"><Mail size={24} aria-hidden="true" /><strong>No matched correspondence yet</strong><p>The engine checks INBOX and Sent for these contact emails on each outreach cycle.</p></div>}
      </section>
      <aside className="client-side-column" aria-label="Client contacts">
        <section className="panel client-playbook-panel"><div className="panel-heading"><div><p className="eyebrow">Client success</p><h2>Prepare a check-in</h2></div><MessageSquareText size={18} aria-hidden="true" /></div>{!playbookData.ready ? <div className="setup-inline"><strong>Playbooks are ready to install</strong><p>Apply migration 030 to prepare approval-gated client drafts.</p></div> : playbookData.playbooks.length ? <ClientPlaybookRunner clientAppId={app.id} contacts={app.contacts.map(contact => ({ id: contact.id, name: contact.name }))} playbooks={playbookData.playbooks.map(playbook => ({ id: playbook.id, name: playbook.name, channel: playbook.channel }))} /> : <div className="empty-state compact-empty"><strong>No active playbooks</strong><p>Create and activate one from the Playbooks page.</p></div>}</section>
        <section className="panel client-stripe-panel"><div className="panel-heading"><div><p className="eyebrow">Stripe</p><h2>Subscription</h2></div><CreditCard size={18} aria-hidden="true" /></div>
          {!data.stripe?.ready ? <div className="setup-inline"><strong>Stripe subscriptions are ready to install</strong><p>Apply migration 028, then link this client’s Stripe customer.</p></div> : <>
            {data.stripe.customerId ? <div className="client-stripe-identity"><strong>{data.stripe.customerName || data.stripe.customerEmail || data.stripe.customerId}</strong><code>{data.stripe.customerId}</code><span className={`status-badge status-${data.stripe.syncStatus}`}>{data.stripe.syncStatus}</span>{data.stripe.lastSyncAt ? <small>Checked {formatWhen(data.stripe.lastSyncAt)}</small> : null}{data.stripe.failureCode ? <small className="action-feedback error">Sync failed · {data.stripe.failureCode}</small> : null}</div> : <p className="muted">Link the Stripe customer to see current and past subscriptions.</p>}
            {data.stripe.subscriptions.length ? <div className="client-subscription-list">{data.stripe.subscriptions.map(subscription => <article key={subscription.id}><header><strong>{subscription.productName || subscription.priceNickname || "Stripe subscription"}</strong><span className={`status-badge status-${subscription.status}`}>{subscription.status.replaceAll("_", " ")}</span></header><code>{subscription.stripeSubscriptionId}</code><dl>{money(subscription.unitAmount, subscription.currency) ? <><dt>Price</dt><dd>{money(subscription.unitAmount, subscription.currency)}{subscription.billingInterval ? ` / ${subscription.intervalCount && subscription.intervalCount > 1 ? `${subscription.intervalCount} ` : ""}${subscription.billingInterval}` : ""}</dd></> : null}{subscription.quantity !== null ? <><dt>Quantity</dt><dd>{subscription.quantity}</dd></> : null}{subscription.currentPeriodEnd ? <><dt>Current period</dt><dd>Ends {formatWhen(subscription.currentPeriodEnd)}</dd></> : null}{subscription.trialEnd ? <><dt>Trial</dt><dd>Ends {formatWhen(subscription.trialEnd)}</dd></> : null}{subscription.cancelAtPeriodEnd ? <><dt>Cancellation</dt><dd>At period end</dd></> : null}{subscription.latestInvoiceStatus ? <><dt>Latest invoice</dt><dd>{subscription.latestInvoiceStatus}</dd></> : null}</dl></article>)}</div> : data.stripe.syncStatus === "synced" ? <div className="empty-state compact-empty"><strong>No subscriptions</strong><p>The linked Stripe customer has no subscriptions.</p></div> : null}
            <ClientStripeLink clientAppId={app.id} currentCustomerId={data.stripe.customerId} />
          </>}
        </section>
        <section className="panel"><div className="panel-heading"><div><p className="eyebrow">People</p><h2>Contacts</h2></div><Users size={18} aria-hidden="true" /></div><div className="client-contact-list">{app.contacts.map(contact => { const assignedUrl = contact.slackStatus === "assigned" && contact.slackTeamId && contact.slackChannelId ? `https://app.slack.com/client/${encodeURIComponent(contact.slackTeamId)}/${encodeURIComponent(contact.slackChannelId)}` : null; const slackUrl = contact.slackStatus === "linked" ? contact.slackChatUrl : assignedUrl; return <article className="client-contact-card" key={contact.id}><header><span><UserRound size={17} aria-hidden="true" /></span><div><strong>{contact.name}</strong><a href={`mailto:${contact.email}`}>{contact.email}</a></div></header><div className="client-contact-sync"><Clock3 size={13} aria-hidden="true" /><span>{contact.lastEmailSyncAt ? `Mailbox checked ${formatWhen(contact.lastEmailSyncAt)}` : "Mailbox match pending"}</span></div>{slackUrl ? <a className="client-slack-link" href={slackUrl} target="_blank" rel="noreferrer"><MessageSquareText size={15} aria-hidden="true" />Open {contact.slackChatLabel || contact.slackDisplayName || contact.slackName || "Slack chat"}<ArrowUpRight size={14} aria-hidden="true" /></a> : <><span className={`client-slack-status status-${contact.slackStatus}`}><MessageSquareText size={14} aria-hidden="true" />{contact.slackStatus === "pending" ? "Slack assignment pending" : contact.slackStatus === "failed" ? `Assignment failed · ${contact.slackFailureCode || "retry available"}` : "No Slack chat assigned"}</span>{contact.slackStatus !== "pending" ? <ClientSlackAssignment clientAppId={app.id} contactId={contact.id} slackName={contact.slackName} status={contact.slackStatus} /> : null}<ClientSlackConnectLink clientAppId={app.id} contactId={contact.id} /></>}</article>; })}</div></section>
        <details className="panel client-add-contact"><summary>Add another contact</summary><ClientContactForm clientAppId={app.id} /></details>
      </aside>
    </div>
  </main>;
}
