-- Four editable EpsiFlow playbook presets with versioned AI instructions.
-- Client and lead drafts remain approval-gated; no delivery permission is added.
BEGIN;

ALTER TABLE client_playbooks ADD COLUMN IF NOT EXISTS preset_key TEXT;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS preset_key TEXT;
ALTER TABLE client_playbook_versions ADD COLUMN IF NOT EXISTS agent_prompt TEXT NOT NULL DEFAULT '';
ALTER TABLE automation_workflow_versions ADD COLUMN IF NOT EXISTS agent_prompt TEXT NOT NULL DEFAULT '';

ALTER TABLE client_playbook_versions DROP CONSTRAINT IF EXISTS client_playbook_versions_agent_prompt_check;
ALTER TABLE client_playbook_versions ADD CONSTRAINT client_playbook_versions_agent_prompt_check CHECK (char_length(agent_prompt) <= 12000);
ALTER TABLE automation_workflow_versions DROP CONSTRAINT IF EXISTS automation_workflow_versions_agent_prompt_check;
ALTER TABLE automation_workflow_versions ADD CONSTRAINT automation_workflow_versions_agent_prompt_check CHECK (char_length(agent_prompt) <= 12000);
CREATE UNIQUE INDEX IF NOT EXISTS client_playbooks_org_preset_key_idx ON client_playbooks(organization_id,preset_key) WHERE preset_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS automation_workflows_org_preset_key_idx ON automation_workflows(organization_id,preset_key) WHERE preset_key IS NOT NULL;

CREATE OR REPLACE FUNCTION dashboard_epsiflow_playbook_library_ready() RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT auth.uid() IS NOT NULL; $$;

DROP FUNCTION IF EXISTS dashboard_create_client_playbook(UUID,TEXT,TEXT,TEXT,TEXT,TEXT[],TEXT[],TEXT[],INTEGER,TEXT,TEXT);
CREATE OR REPLACE FUNCTION dashboard_create_client_playbook(target_organization_id UUID,target_name TEXT,target_description TEXT,target_channel TEXT,target_trigger_type TEXT,target_eligible_statuses TEXT[],target_eligible_segments TEXT[],target_eligible_relationships TEXT[],target_cooldown_days INTEGER,target_subject_template TEXT,target_body_template TEXT,target_agent_prompt TEXT)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE new_id UUID; normalized_subject TEXT; clean_template TEXT;
BEGIN
 IF auth.uid() IS NULL OR NOT dashboard_has_org_role(target_organization_id,ARRAY['admin']) THEN RAISE EXCEPTION 'Administrator access required'; END IF;
 IF char_length(trim(COALESCE(target_name,''))) NOT BETWEEN 3 AND 120 OR char_length(COALESCE(target_description,''))>500 OR target_channel NOT IN ('email','slack') OR target_trigger_type NOT IN ('manual_client_checkin','scheduled_checkin','stripe_cancellation','churn_reactivation') THEN RAISE EXCEPTION 'Invalid playbook identity'; END IF;
 IF NOT COALESCE(target_eligible_statuses,'{}') <@ ARRAY['none','incomplete','incomplete_expired','trialing','active','past_due','canceled','unpaid','paused']::TEXT[] OR NOT COALESCE(target_eligible_segments,'{}') <@ ARRAY['epsiflow_direct','stripe_plan']::TEXT[] OR cardinality(target_eligible_segments)=0 OR NOT COALESCE(target_eligible_relationships,'{}') <@ ARRAY['active','churned']::TEXT[] OR cardinality(target_eligible_relationships)=0 OR target_cooldown_days NOT BETWEEN 1 AND 365 THEN RAISE EXCEPTION 'Invalid playbook conditions'; END IF;
 normalized_subject:=NULLIF(trim(COALESCE(target_subject_template,'')),''); IF target_channel='email' AND (normalized_subject IS NULL OR char_length(normalized_subject)>998) THEN RAISE EXCEPTION 'Email playbooks require a subject'; END IF; IF target_channel='slack' THEN normalized_subject:=NULL; END IF;
 IF char_length(trim(COALESCE(target_body_template,''))) NOT BETWEEN 1 AND 10000 OR char_length(trim(COALESCE(target_agent_prompt,''))) NOT BETWEEN 20 AND 12000 THEN RAISE EXCEPTION 'Invalid playbook content'; END IF;
 clean_template:=COALESCE(normalized_subject,'')||target_body_template; clean_template:=replace(replace(replace(replace(replace(replace(clean_template,'{{clientName}}',''),'{{contactName}}',''),'{{contactFirstName}}',''),'{{subscriptionStatus}}',''),'{{productName}}',''),'{{billingInterval}}',''); IF clean_template ~ '\{\{[^}]+\}\}' THEN RAISE EXCEPTION 'Unsupported template variable'; END IF;
 INSERT INTO client_playbooks(organization_id,name,description,channel,trigger_type,eligible_subscription_statuses,eligible_client_segments,eligible_relationship_states,cooldown_days,created_by_user_id,updated_by_user_id) VALUES(target_organization_id,trim(target_name),trim(COALESCE(target_description,'')),target_channel,target_trigger_type,COALESCE(target_eligible_statuses,'{}'),target_eligible_segments,target_eligible_relationships,target_cooldown_days,auth.uid(),auth.uid()) RETURNING id INTO new_id;
 INSERT INTO client_playbook_versions(playbook_id,version,subject_template,body_template,agent_prompt,definition,created_by_user_id) VALUES(new_id,1,normalized_subject,trim(target_body_template),trim(target_agent_prompt),jsonb_build_object('trigger',target_trigger_type,'channel',target_channel,'eligible_subscription_statuses',COALESCE(target_eligible_statuses,'{}'),'eligible_client_segments',target_eligible_segments,'eligible_relationship_states',target_eligible_relationships,'cooldown_days',target_cooldown_days,'approval','required'),auth.uid());
 INSERT INTO audit_events(organization_id,actor_user_id,event_type,target_type,target_id,metadata) VALUES(target_organization_id,auth.uid(),'client.playbook.created','client_playbook',new_id::TEXT,jsonb_build_object('version',1,'status','draft','channel',target_channel,'trigger',target_trigger_type)); RETURN new_id;
EXCEPTION WHEN unique_violation THEN RAISE EXCEPTION 'A playbook with this name already exists'; END; $$;

CREATE OR REPLACE FUNCTION dashboard_update_client_playbook(target_playbook_id UUID,target_name TEXT,target_description TEXT,target_channel TEXT,target_trigger_type TEXT,target_eligible_statuses TEXT[],target_eligible_segments TEXT[],target_eligible_relationships TEXT[],target_cooldown_days INTEGER,target_subject_template TEXT,target_body_template TEXT,target_agent_prompt TEXT)
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE target client_playbooks%ROWTYPE; next_version INTEGER; normalized_subject TEXT; clean_template TEXT;
BEGIN
 SELECT * INTO target FROM client_playbooks WHERE id=target_playbook_id FOR UPDATE;
 IF NOT FOUND OR auth.uid() IS NULL OR NOT dashboard_has_org_role(target.organization_id,ARRAY['admin']) THEN RAISE EXCEPTION 'Playbook not found'; END IF;
 IF target.status='active' THEN RAISE EXCEPTION 'Pause the playbook before editing'; END IF;
 IF char_length(trim(COALESCE(target_name,''))) NOT BETWEEN 3 AND 120 OR char_length(COALESCE(target_description,''))>500 OR target_channel NOT IN ('email','slack') OR target_trigger_type NOT IN ('manual_client_checkin','scheduled_checkin','stripe_cancellation','churn_reactivation') THEN RAISE EXCEPTION 'Invalid playbook identity'; END IF;
 IF NOT COALESCE(target_eligible_statuses,'{}') <@ ARRAY['none','incomplete','incomplete_expired','trialing','active','past_due','canceled','unpaid','paused']::TEXT[] OR NOT COALESCE(target_eligible_segments,'{}') <@ ARRAY['epsiflow_direct','stripe_plan']::TEXT[] OR cardinality(target_eligible_segments)=0 OR NOT COALESCE(target_eligible_relationships,'{}') <@ ARRAY['active','churned']::TEXT[] OR cardinality(target_eligible_relationships)=0 OR target_cooldown_days NOT BETWEEN 1 AND 365 THEN RAISE EXCEPTION 'Invalid playbook conditions'; END IF;
 normalized_subject:=NULLIF(trim(COALESCE(target_subject_template,'')),''); IF target_channel='email' AND (normalized_subject IS NULL OR char_length(normalized_subject)>998) THEN RAISE EXCEPTION 'Email playbooks require a subject'; END IF; IF target_channel='slack' THEN normalized_subject:=NULL; END IF;
 IF char_length(trim(COALESCE(target_body_template,''))) NOT BETWEEN 1 AND 10000 OR char_length(trim(COALESCE(target_agent_prompt,''))) NOT BETWEEN 20 AND 12000 THEN RAISE EXCEPTION 'Invalid playbook content'; END IF;
 clean_template:=COALESCE(normalized_subject,'')||target_body_template; clean_template:=replace(replace(replace(replace(replace(replace(clean_template,'{{clientName}}',''),'{{contactName}}',''),'{{contactFirstName}}',''),'{{subscriptionStatus}}',''),'{{productName}}',''),'{{billingInterval}}',''); IF clean_template ~ '\{\{[^}]+\}\}' THEN RAISE EXCEPTION 'Unsupported template variable'; END IF;
 next_version:=target.current_version+1;
 UPDATE client_playbooks SET name=trim(target_name),description=trim(COALESCE(target_description,'')),channel=target_channel,trigger_type=target_trigger_type,eligible_subscription_statuses=COALESCE(target_eligible_statuses,'{}'),eligible_client_segments=target_eligible_segments,eligible_relationship_states=target_eligible_relationships,cooldown_days=target_cooldown_days,current_version=next_version,updated_by_user_id=auth.uid() WHERE id=target_playbook_id;
 INSERT INTO client_playbook_versions(playbook_id,version,subject_template,body_template,agent_prompt,definition,created_by_user_id) VALUES(target_playbook_id,next_version,normalized_subject,trim(target_body_template),trim(target_agent_prompt),jsonb_build_object('trigger',target_trigger_type,'channel',target_channel,'eligible_subscription_statuses',COALESCE(target_eligible_statuses,'{}'),'eligible_client_segments',target_eligible_segments,'eligible_relationship_states',target_eligible_relationships,'cooldown_days',target_cooldown_days,'approval','required'),auth.uid());
 INSERT INTO audit_events(organization_id,actor_user_id,event_type,target_type,target_id,metadata) VALUES(target.organization_id,auth.uid(),'client.playbook.version_created','client_playbook',target_playbook_id::TEXT,jsonb_build_object('previous_version',target.current_version,'version',next_version)); RETURN next_version;
EXCEPTION WHEN unique_violation THEN RAISE EXCEPTION 'A playbook with this name already exists'; END; $$;

DROP FUNCTION IF EXISTS dashboard_create_reply_workflow(UUID,TEXT,TEXT,TEXT,INTEGER);
CREATE OR REPLACE FUNCTION dashboard_create_reply_workflow(target_organization_id UUID,workflow_name TEXT,workflow_description TEXT,workflow_body_template TEXT,workflow_delay_minutes INTEGER,workflow_agent_prompt TEXT)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE new_id UUID; definition JSONB;
BEGIN
 IF auth.uid() IS NULL OR NOT dashboard_has_org_role(target_organization_id,ARRAY['admin']) THEN RAISE EXCEPTION 'Administrator access required'; END IF;
 IF char_length(trim(COALESCE(workflow_name,''))) NOT BETWEEN 3 AND 120 OR char_length(COALESCE(workflow_description,''))>500 OR char_length(trim(COALESCE(workflow_body_template,''))) NOT BETWEEN 1 AND 10000 OR workflow_delay_minutes NOT BETWEEN 0 AND 10080 OR char_length(trim(COALESCE(workflow_agent_prompt,''))) NOT BETWEEN 20 AND 12000 THEN RAISE EXCEPTION 'Invalid workflow definition'; END IF;
 definition:=jsonb_build_object('trigger',jsonb_build_object('type','prospect_reply_received'),'conditions',jsonb_build_array(jsonb_build_object('field','prospect.status','operator','equals','value','active')),'steps',jsonb_build_array(jsonb_build_object('key','prepare_reply','type','prepare_email_reply','approval','required','delay_minutes',workflow_delay_minutes)),'stop_conditions',jsonb_build_array('workflow_paused','prospect_inactive','reply_context_missing'));
 INSERT INTO automation_workflows(organization_id,name,description,trigger_type,delay_minutes,created_by_user_id,updated_by_user_id) VALUES(target_organization_id,trim(workflow_name),trim(COALESCE(workflow_description,'')),'prospect_reply_received',workflow_delay_minutes,auth.uid(),auth.uid()) RETURNING id INTO new_id;
 INSERT INTO automation_workflow_versions(workflow_id,version,body_template,agent_prompt,definition,created_by_user_id) VALUES(new_id,1,trim(workflow_body_template),trim(workflow_agent_prompt),definition,auth.uid());
 INSERT INTO audit_events(organization_id,actor_user_id,event_type,target_type,target_id,metadata) VALUES(target_organization_id,auth.uid(),'automation.workflow.created','automation_workflow',new_id::TEXT,jsonb_build_object('version',1,'status','draft','trigger_type','prospect_reply_received')); RETURN new_id;
END; $$;

DROP FUNCTION IF EXISTS dashboard_update_reply_workflow(UUID,TEXT,TEXT,TEXT,INTEGER);
CREATE OR REPLACE FUNCTION dashboard_update_reply_workflow(target_workflow_id UUID,workflow_name TEXT,workflow_description TEXT,workflow_body_template TEXT,workflow_delay_minutes INTEGER,workflow_agent_prompt TEXT)
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE target automation_workflows%ROWTYPE; next_version INTEGER; definition JSONB;
BEGIN
 SELECT * INTO target FROM automation_workflows WHERE id=target_workflow_id FOR UPDATE;
 IF NOT FOUND OR auth.uid() IS NULL OR NOT dashboard_has_org_role(target.organization_id,ARRAY['admin']) THEN RAISE EXCEPTION 'Workflow not found'; END IF;
 IF target.status='active' THEN RAISE EXCEPTION 'Pause the workflow before editing'; END IF;
 IF char_length(trim(COALESCE(workflow_name,''))) NOT BETWEEN 3 AND 120 OR char_length(COALESCE(workflow_description,''))>500 OR char_length(trim(COALESCE(workflow_body_template,''))) NOT BETWEEN 1 AND 10000 OR workflow_delay_minutes NOT BETWEEN 0 AND 10080 OR char_length(trim(COALESCE(workflow_agent_prompt,''))) NOT BETWEEN 20 AND 12000 THEN RAISE EXCEPTION 'Invalid workflow definition'; END IF;
 next_version:=target.current_version+1; definition:=jsonb_build_object('trigger',jsonb_build_object('type','prospect_reply_received'),'conditions',jsonb_build_array(jsonb_build_object('field','prospect.status','operator','equals','value','active')),'steps',jsonb_build_array(jsonb_build_object('key','prepare_reply','type','prepare_email_reply','approval','required','delay_minutes',workflow_delay_minutes)),'stop_conditions',jsonb_build_array('workflow_paused','prospect_inactive','reply_context_missing'));
 UPDATE automation_workflows SET name=trim(workflow_name),description=trim(COALESCE(workflow_description,'')),delay_minutes=workflow_delay_minutes,current_version=next_version,updated_by_user_id=auth.uid() WHERE id=target_workflow_id;
 INSERT INTO automation_workflow_versions(workflow_id,version,body_template,agent_prompt,definition,created_by_user_id) VALUES(target_workflow_id,next_version,trim(workflow_body_template),trim(workflow_agent_prompt),definition,auth.uid());
 INSERT INTO audit_events(organization_id,actor_user_id,event_type,target_type,target_id,metadata) VALUES(target.organization_id,auth.uid(),'automation.workflow.version_created','automation_workflow',target_workflow_id::TEXT,jsonb_build_object('previous_version',target.current_version,'version',next_version)); RETURN next_version;
END; $$;

DROP FUNCTION IF EXISTS service_claim_client_playbook_agent_drafts(INTEGER);
CREATE OR REPLACE FUNCTION service_claim_client_playbook_agent_drafts(target_limit INTEGER DEFAULT 3)
RETURNS TABLE(id UUID,organization_id UUID,client_app_id UUID,client_contact_id UUID,channel TEXT,playbook_name TEXT,playbook_description TEXT,trigger_type TEXT,subject_template TEXT,body_template TEXT,agent_prompt TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF auth.role() IS DISTINCT FROM 'service_role' THEN RAISE EXCEPTION 'Service role required'; END IF;
 IF target_limit NOT BETWEEN 1 AND 10 THEN RAISE EXCEPTION 'Invalid limit'; END IF;
 UPDATE client_playbook_drafts draft SET agent_status='failed',agent_failure_code='agent_attempts_exhausted',agent_claimed_at=NULL WHERE draft.status='draft' AND draft.agent_status='processing' AND draft.agent_claimed_at<NOW()-INTERVAL '15 minutes' AND draft.agent_attempt_count>=3;
 UPDATE client_playbook_drafts draft SET agent_status='pending',agent_failure_code='stale_claim_recovered',agent_claimed_at=NULL WHERE draft.status='draft' AND draft.agent_status='processing' AND draft.agent_claimed_at<NOW()-INTERVAL '15 minutes' AND draft.agent_attempt_count<3;
 RETURN QUERY WITH candidates AS (
  SELECT draft.id FROM client_playbook_drafts draft JOIN client_playbooks playbook ON playbook.id=draft.playbook_id AND playbook.status='active' JOIN client_apps app ON app.id=draft.client_app_id AND app.organization_id=draft.organization_id AND app.status='active' AND app.client_success_enabled=TRUE AND app.relationship_state<>'closed' AND app.client_segment=ANY(playbook.eligible_client_segments) AND app.relationship_state=ANY(playbook.eligible_relationship_states) JOIN client_contacts contact ON contact.id=draft.client_contact_id AND contact.client_app_id=app.id AND contact.organization_id=draft.organization_id AND (draft.channel='email' OR contact.slack_assignment_status IN ('assigned','linked')) LEFT JOIN LATERAL(SELECT subscription.status FROM client_subscriptions subscription WHERE subscription.client_app_id=app.id ORDER BY CASE subscription.status WHEN 'active' THEN 1 WHEN 'trialing' THEN 2 WHEN 'past_due' THEN 3 WHEN 'unpaid' THEN 4 ELSE 5 END,subscription.synced_at DESC LIMIT 1) current_subscription ON TRUE JOIN automation_runtime_controls control ON control.organization_id=draft.organization_id AND control.globally_paused=FALSE WHERE draft.status='draft' AND draft.agent_status IN ('not_requested','pending') AND draft.agent_attempt_count<3 AND (cardinality(playbook.eligible_subscription_statuses)=0 OR COALESCE(current_subscription.status,'none')=ANY(playbook.eligible_subscription_statuses)) AND (playbook.trigger_type<>'stripe_cancellation' OR current_subscription.status='canceled') AND (playbook.trigger_type<>'churn_reactivation' OR app.relationship_state='churned') ORDER BY draft.created_at FOR UPDATE OF draft SKIP LOCKED LIMIT target_limit
 ),claimed AS (UPDATE client_playbook_drafts draft SET agent_status='processing',agent_attempt_count=agent_attempt_count+1,agent_claimed_at=NOW(),agent_failure_code=NULL FROM candidates WHERE draft.id=candidates.id RETURNING draft.*)
 SELECT claimed.id,claimed.organization_id,claimed.client_app_id,claimed.client_contact_id,claimed.channel,playbook.name,playbook.description,playbook.trigger_type,version.subject_template,version.body_template,version.agent_prompt FROM claimed JOIN client_playbooks playbook ON playbook.id=claimed.playbook_id JOIN client_playbook_versions version ON version.playbook_id=claimed.playbook_id AND version.version=claimed.playbook_version;
END; $$;

DO $seed$
DECLARE org RECORD; admin_id UUID; new_id UUID;
DECLARE health_prompt TEXT := $p$Review the complete client conversation and CRM/subscription context. Draft a warm relationship check-in that refers naturally to the latest relevant topic or unresolved commitment. Ask how Shopify Ads or the client's current growth work is going and whether EpsiFlow can remove a blocker. Do not turn this into a generic sales pitch. Use one clear, low-friction question and do not repeat a question already answered in the conversation.$p$;
DECLARE direct_prompt TEXT := $p$This client is manually classified as an active EpsiFlow Direct customer. The CRM relationship state is authoritative even when Stripe says canceled. Review all conversation and billing context. Prepare a respectful monthly payment check that asks for confirmation or identifies a blocker, but never state that payment is overdue, missing, or received unless the evidence proves it. Do not invent an amount, due date, invoice, balance, fee, or payment link. Keep the relationship helpful and use one clear next step.$p$;
DECLARE stripe_prompt TEXT := $p$This active client uses a Stripe-funded plan and the recorded subscription is canceled, past due, unpaid, incomplete, or expired. Review all conversation and subscription context. Ask what caused the pause or payment problem and whether the client wants help resuming. Mention a smaller plan or alternative only as an option to discuss; never invent plan names, prices, discounts, payment status, or financial terms. Acknowledge prior objections and use one low-pressure question.$p$;
DECLARE lead_prompt TEXT := $p$Review the complete lead conversation and answer the latest question directly. Explain EpsiFlow in outcome-first language: it helps Shopify app companies, especially in India, launch and run Shopify Ads without payment setup becoming the bottleneck, with related funding, spend, invoice, onboarding, and support workflows. Tailor the explanation to what the lead already knows. Do not invent pricing, fees, custody, refund terms, legal coverage, availability, acceptance rates, or product capabilities. If the question requires an unconfirmed fact, say it needs confirmation. End with one relevant, low-friction next step.$p$;
BEGIN
 FOR org IN SELECT id FROM organizations LOOP
  SELECT user_id INTO admin_id FROM organization_members WHERE organization_id=org.id AND role='admin' AND status='active' ORDER BY created_at LIMIT 1;
  IF admin_id IS NULL THEN CONTINUE; END IF;

  new_id:=NULL; INSERT INTO client_playbooks(organization_id,name,description,channel,trigger_type,eligible_subscription_statuses,eligible_client_segments,eligible_relationship_states,cooldown_days,status,preset_key,created_by_user_id,updated_by_user_id) VALUES(org.id,'Monthly client health check','Warm active clients by checking campaign progress, current priorities, and support needs.','email','scheduled_checkin','{}',ARRAY['epsiflow_direct','stripe_plan'],ARRAY['active'],30,'draft','client_health_monthly',admin_id,admin_id) ON CONFLICT DO NOTHING RETURNING id INTO new_id;
  IF new_id IS NOT NULL THEN INSERT INTO client_playbook_versions(playbook_id,version,subject_template,body_template,agent_prompt,definition,created_by_user_id) VALUES(new_id,1,'How are things going with {{clientName}}?',E'Hi {{contactFirstName}},\n\nI wanted to check in and see how things are going with {{clientName}}. How are your current advertising or growth priorities progressing, and is there anything you would like us to help unblock?\n\nBest,\nEpsiFlow',health_prompt,jsonb_build_object('trigger','scheduled_checkin','channel','email','eligible_client_segments',ARRAY['epsiflow_direct','stripe_plan'],'eligible_relationship_states',ARRAY['active'],'cooldown_days',30,'approval','required'),admin_id); END IF;

  new_id:=NULL; INSERT INTO client_playbooks(organization_id,name,description,channel,trigger_type,eligible_subscription_statuses,eligible_client_segments,eligible_relationship_states,cooldown_days,status,preset_key,created_by_user_id,updated_by_user_id) VALUES(org.id,'EpsiFlow Direct monthly payment check','Follow up with active Direct customers about their monthly subscription payment without trusting Stripe cancellation as churn.','email','scheduled_checkin','{}',ARRAY['epsiflow_direct'],ARRAY['active'],30,'draft','direct_payment_monthly',admin_id,admin_id) ON CONFLICT DO NOTHING RETURNING id INTO new_id;
  IF new_id IS NOT NULL THEN INSERT INTO client_playbook_versions(playbook_id,version,subject_template,body_template,agent_prompt,definition,created_by_user_id) VALUES(new_id,1,'EpsiFlow Direct monthly check for {{clientName}}',E'Hi {{contactFirstName}},\n\nI am checking in regarding this month’s EpsiFlow Direct subscription for {{clientName}}. Could you let me know whether everything is on track or if there is anything blocking the payment?\n\nBest,\nEpsiFlow',direct_prompt,jsonb_build_object('trigger','scheduled_checkin','channel','email','eligible_client_segments',ARRAY['epsiflow_direct'],'eligible_relationship_states',ARRAY['active'],'cooldown_days',30,'approval','required'),admin_id); END IF;

  new_id:=NULL; INSERT INTO client_playbooks(organization_id,name,description,channel,trigger_type,eligible_subscription_statuses,eligible_client_segments,eligible_relationship_states,cooldown_days,status,preset_key,created_by_user_id,updated_by_user_id) VALUES(org.id,'Stripe plan payment and cancellation recovery','Understand failed, unpaid, incomplete, or canceled Stripe plans and offer a relevant path back.','email','scheduled_checkin',ARRAY['past_due','unpaid','incomplete','incomplete_expired','canceled'],ARRAY['stripe_plan'],ARRAY['active'],14,'draft','stripe_plan_recovery',admin_id,admin_id) ON CONFLICT DO NOTHING RETURNING id INTO new_id;
  IF new_id IS NOT NULL THEN INSERT INTO client_playbook_versions(playbook_id,version,subject_template,body_template,agent_prompt,definition,created_by_user_id) VALUES(new_id,1,'Can we help with your EpsiFlow plan?',E'Hi {{contactFirstName}},\n\nI noticed that the current {{productName}} subscription status is {{subscriptionStatus}}. Was there a payment issue or a change in what {{clientName}} needs right now? If useful, we can discuss a better-fit option.\n\nBest,\nEpsiFlow',stripe_prompt,jsonb_build_object('trigger','scheduled_checkin','channel','email','eligible_subscription_statuses',ARRAY['past_due','unpaid','incomplete','incomplete_expired','canceled'],'eligible_client_segments',ARRAY['stripe_plan'],'eligible_relationship_states',ARRAY['active'],'cooldown_days',14,'approval','required'),admin_id); END IF;

  new_id:=NULL; INSERT INTO automation_workflows(organization_id,name,description,status,trigger_type,delay_minutes,preset_key,created_by_user_id,updated_by_user_id) VALUES(org.id,'New lead education and onboarding','Answer recurring lead questions about what EpsiFlow does, onboarding, and available options using the full conversation.','draft','prospect_reply_received',15,'lead_education_reply',admin_id,admin_id) ON CONFLICT DO NOTHING RETURNING id INTO new_id;
  IF new_id IS NOT NULL THEN INSERT INTO automation_workflow_versions(workflow_id,version,body_template,agent_prompt,definition,created_by_user_id) VALUES(new_id,1,E'Hi {{firstName}},\n\nThanks for your question. EpsiFlow helps Shopify app companies access the payment setup and operating support needed to run Shopify Ads. I can explain the relevant setup and next steps based on what {{company}} needs.\n\nBest,\nEpsiFlow',lead_prompt,jsonb_build_object('trigger',jsonb_build_object('type','prospect_reply_received'),'conditions',jsonb_build_array(jsonb_build_object('field','prospect.status','operator','equals','value','active')),'steps',jsonb_build_array(jsonb_build_object('key','prepare_reply','type','prepare_email_reply','approval','required','delay_minutes',15)),'stop_conditions',jsonb_build_array('workflow_paused','prospect_inactive','reply_context_missing')),admin_id); END IF;
 END LOOP;
END $seed$;

REVOKE ALL ON FUNCTION dashboard_create_client_playbook(UUID,TEXT,TEXT,TEXT,TEXT,TEXT[],TEXT[],TEXT[],INTEGER,TEXT,TEXT,TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION dashboard_epsiflow_playbook_library_ready() FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION dashboard_update_client_playbook(UUID,TEXT,TEXT,TEXT,TEXT,TEXT[],TEXT[],TEXT[],INTEGER,TEXT,TEXT,TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION dashboard_create_reply_workflow(UUID,TEXT,TEXT,TEXT,INTEGER,TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION dashboard_update_reply_workflow(UUID,TEXT,TEXT,TEXT,INTEGER,TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION service_claim_client_playbook_agent_drafts(INTEGER) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION dashboard_create_client_playbook(UUID,TEXT,TEXT,TEXT,TEXT,TEXT[],TEXT[],TEXT[],INTEGER,TEXT,TEXT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION dashboard_epsiflow_playbook_library_ready() TO authenticated;
GRANT EXECUTE ON FUNCTION dashboard_update_client_playbook(UUID,TEXT,TEXT,TEXT,TEXT,TEXT[],TEXT[],TEXT[],INTEGER,TEXT,TEXT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION dashboard_create_reply_workflow(UUID,TEXT,TEXT,TEXT,INTEGER,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION dashboard_update_reply_workflow(UUID,TEXT,TEXT,TEXT,INTEGER,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION service_claim_client_playbook_agent_drafts(INTEGER) TO service_role;

COMMIT;
