import type { Metadata } from "next";
import Link from "next/link";
import { CheckCheck, CircleStop, GitBranch, Mail, MessageSquareText, PlayCircle, ShieldCheck, Workflow } from "lucide-react";
import { requireMembership } from "../../../lib/auth";
import { createSupabaseServerClient } from "../../../lib/supabase-server";
import { getClientPlaybooks } from "../../../lib/client-playbook-data";
import { ClientPlaybookBuilder, ClientPlaybookStatusControl } from "../../components/client-playbook-controls";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Client playbooks" };
const triggerLabels: Record<string, string> = { manual_client_checkin: "Manual", scheduled_checkin: "Scheduled check-in", stripe_cancellation: "Stripe cancellation", churn_reactivation: "Churn reactivation" };

export default async function PlaybooksPage() {
  const { membership } = await requireMembership(); if (!membership) return null;
  const supabase = await createSupabaseServerClient(); if (!supabase) throw new Error("Dashboard authentication is not configured.");
  const data = await getClientPlaybooks(supabase, membership.organization.id); const isAdmin = membership.role === "admin";
  return <main className="dashboard-main" id="main-content">
    <header className="page-header"><div><p className="eyebrow">Client success</p><h1>Playbooks</h1><p className="page-summary">Turn subscription and CRM context into consistent, reviewable client communication.</p></div><div className="page-header-actions"><span className="record-count">{data.playbooks.length} playbooks</span><Link className="secondary-button compact-button header-action" href="/dashboard/approvals"><CheckCheck size={15} aria-hidden="true" />Review drafts</Link></div></header>
    {!data.ready ? <section className="panel setup-panel"><Workflow size={20} aria-hidden="true" /><div><strong>Scheduled client playbooks are ready to install</strong><p>Apply migration 032 to enable trigger, audience, cooldown, and scheduled-draft controls.</p></div></section> : null}
    <section className="playbook-safety" aria-labelledby="playbook-safety-heading"><ShieldCheck size={21} aria-hidden="true" /><div><p className="eyebrow">Current boundary</p><h2 id="playbook-safety-heading">Draft preparation only</h2><p>Running or approving a playbook does not send email or Slack. Provider delivery will be installed separately with another revalidation checkpoint.</p></div></section>
    <section className="automation-section" aria-labelledby="playbook-list-heading"><div className="section-heading"><div><p className="eyebrow">Definitions</p><h2 id="playbook-list-heading">Client-success playbooks</h2></div><span className="count-badge">{data.playbooks.length}</span></div>
      {data.playbooks.length ? <div className="playbook-list">{data.playbooks.map(playbook => <article className="playbook-card" key={playbook.id}><header><span className={`playbook-channel channel-${playbook.channel}`}>{playbook.channel === "email" ? <Mail size={18} aria-hidden="true" /> : <MessageSquareText size={18} aria-hidden="true" />}</span><div><span className={`status-badge status-${playbook.status}`}>{playbook.status}</span><h3>{playbook.name}</h3><p>{playbook.description || "No description"}</p></div><div className="workflow-version"><span>Version</span><strong>v{playbook.currentVersion}</strong><small>{playbook.versions} immutable snapshot{playbook.versions === 1 ? "" : "s"}</small></div></header><div className="playbook-path"><span><GitBranch size={15} aria-hidden="true" /><small>Trigger and audience</small><strong>{triggerLabels[playbook.triggerType] || playbook.triggerType} · {playbook.eligibleSegments.map((value: string) => value.replaceAll("_", " ")).join(", ")} · {playbook.eligibleRelationships.join(", ")}{playbook.triggerType === "manual_client_checkin" ? "" : ` · ${playbook.cooldownDays}d cooldown`}</strong><small>{playbook.eligibleStatuses.length ? `Subscriptions: ${playbook.eligibleStatuses.map((status: string) => status.replaceAll("_", " ")).join(", ")}` : "Any subscription state"}</small></span><span><Workflow size={15} aria-hidden="true" /><small>Action</small><strong>Prepare {playbook.channel} draft</strong></span><span><CheckCheck size={15} aria-hidden="true" /><small>Checkpoint</small><strong>Human approval</strong></span></div><footer><span><CircleStop size={14} aria-hidden="true" />No delivery installed</span>{isAdmin ? <ClientPlaybookStatusControl id={playbook.id} status={playbook.status} /> : <span className="campaign-locked">Admin managed</span>}</footer></article>)}</div> : <div className="empty-state automation-empty"><PlayCircle size={24} aria-hidden="true" /><strong>No client playbooks yet</strong><p>Create the first definition below. It remains inactive until an administrator enables it.</p></div>}
    </section>
    <section className="automation-layout"><article className="panel workflow-builder-panel"><div className="panel-heading"><div><p className="eyebrow">New definition</p><h2>Client-success playbook</h2></div><Workflow size={18} aria-hidden="true" /></div><p className="workflow-builder-copy">Choose the trigger, CRM audience, subscription states, cooldown, and reusable email or Slack template.</p><ClientPlaybookBuilder isAdmin={isAdmin} /></article><article className="panel automation-safety"><div className="panel-heading"><div><p className="eyebrow">How to use it</p><h2>From signal to approval</h2></div><ShieldCheck size={18} aria-hidden="true" /></div><ol className="playbook-steps"><li><strong>1</strong><span>Create and review the trigger, audience, and wording.</span></li><li><strong>2</strong><span>Activate the playbook. Automatic preparation remains behind its server kill switch.</span></li><li><strong>3</strong><span>A matching signal prepares one version-pinned draft within the cooldown.</span></li><li><strong>4</strong><span>Edit, approve, or cancel it in Approvals. No provider delivery is installed.</span></li></ol></article></section>
  </main>;
}
